// Generic fixed questions for specialties without a dedicated pack.
// Translations: text_XX / label_XX for each language code (hard-coded, no LLM).

export const GENERIC_QUESTIONS = [
  {
    id: "health_issue",
    kind: "fixed",
    type: "text",
    text: "What is the health issue you are facing now?",
    text_kn: "ನೀವು ಈಗ ಎದುರಿಸುತ್ತಿರುವ ಆರೋಗ್ಯ ಸಮಸ್ಯೆ ಏನು?",
    text_hi: "आप अभी किस स्वास्थ्य समस्या का सामना कर रहे हैं?",
    text_ta: "நீங்கள் இப்போது எதிர்கொள்ளும் உடல்நலப் பிரச்சினை என்ன?",
    text_te: "మీరు ప్రస్తుతం ఎదుర్కొంటున్న ఆరోగ్య సమస్య ఏమిటి?",
    text_ml: "നിങ്ങൾ ഇപ്പോൾ നേരിടുന്ന ആരോഗ്യ പ്രശ്നം എന്താണ്?",
    text_bn: "আপনি এখন কোন স্বাস্থ্য সমস্যার সম্মুখীন?",
    text_or: "ଆପଣ ବର୍ତ୍ତମାନ କେଉଁ ସ୍ୱାସ୍ଥ୍ୟ ସମସ୍ୟା ସମ୍ମୁଖୀନ?",
    text_as: "আপুনি এতিয়া কোন স্বাস্থ্য সমস্যাৰ সন্মুখীন?",
    text_mr: "तुम्ही सध्या कोणत्या आरोग्य समस्येचा सामना करत आहात?",
    text_ur: "آپ اس وقت کس صحت کے مسئلے کا سامنا کر رہے ہیں؟",
    text_bho: "रउआ अब का स्वास्थ्य समस्या झेलत बानी?",
    text_mai: "अहाँ अखन कोन स्वास्थ्य समस्या सँ गुजरि रहल छी?",
    text_ne: "तपाईं अहिले कुन स्वास्थ्य समस्याको सामना गर्दै हुनुहुन्छ?",
    text_mni: "নহাক্না হৌজিক করি হকচংগী খুদোংচাদা লৈরিবগে?",
    text_brx: "नोंथां दानो मा स्वास्थ्य जोंगनायाव गोनां?",
  },

  {
    id: "symptom_since",
    kind: "fixed",
    type: "single",
    text: "Since when?",
    text_kn: "ಯಾವಾಗಿನಿಂದ?",
    text_hi: "कब से?",
    text_ta: "எப்போதிருந்து?",
    text_te: "ఎప్పటి నుండి?",
    text_ml: "എപ്പോൾ മുതൽ?",
    text_bn: "কবে থেকে?",
    text_or: "କେବେଠାରୁ?",
    text_as: "কেতিয়াৰ পৰা?",
    text_mr: "केव्हापासून?",
    text_ur: "کب سے؟",
    text_bho: "कब से?",
    text_mai: "कब सँ?",
    text_ne: "कहिलेदेखि?",
    text_mni: "করিগীদগী?",
    text_brx: "माब्ला निफ्राय?",
    options: [
      { id: "d1_2", label: "1-2 days", label_kn: "೧-೨ ದಿನ", label_hi: "1-2 दिन", label_ta: "1-2 நாட்கள்", label_te: "1-2 రోజులు", label_ml: "1-2 ദിവസം", label_bn: "১-২ দিন", label_or: "୧-୨ ଦିନ", label_as: "১-২ দিন", label_mr: "१-२ दिवस", label_ur: "1-2 دن", label_bho: "1-2 दिन", label_mai: "1-2 दिन", label_ne: "१-२ दिन", label_mni: "১-২ নুমিৎ", label_brx: "1-2 सान" },
      { id: "d3_5", label: "3-5 days", label_kn: "೩-೫ ದಿನ", label_hi: "3-5 दिन", label_ta: "3-5 நாட்கள்", label_te: "3-5 రోజులు", label_ml: "3-5 ദിവസം", label_bn: "৩-৫ দিন", label_or: "୩-୫ ଦିନ", label_as: "৩-৫ দিন", label_mr: "३-५ दिवस", label_ur: "3-5 دن", label_bho: "3-5 दिन", label_mai: "3-5 दिन", label_ne: "३-५ दिन", label_mni: "৩-৫ নুমিৎ", label_brx: "3-5 सान" },
      { id: "d6_8", label: "6-8 days", label_kn: "೬-೮ ದಿನ", label_hi: "6-8 दिन", label_ta: "6-8 நாட்கள்", label_te: "6-8 రోజులు", label_ml: "6-8 ദിവസം", label_bn: "৬-৮ দিন", label_or: "୬-୮ ଦିନ", label_as: "৬-৮ দিন", label_mr: "६-८ दिवस", label_ur: "6-8 دن", label_bho: "6-8 दिन", label_mai: "6-8 दिन", label_ne: "६-८ दिन", label_mni: "৬-৮ নুমিৎ", label_brx: "6-8 सान" },
    ],
  },

  {
    id: "current_medication",
    kind: "fixed",
    type: "text",
    text: "What medication are you already taking?",
    text_kn: "ನೀವು ಈಗಾಗಲೇ ಯಾವ ಔಷಧ ತೆಗೆದುಕೊಳ್ಳುತ್ತಿದ್ದೀರಿ?",
    text_hi: "आप पहले से कौन सी दवा ले रहे हैं?",
    text_ta: "நீங்கள் ஏற்கனவே எந்த மருந்து எடுத்துக்கொள்கிறீர்கள்?",
    text_te: "మీరు ఇప్పటికే ఏ మందు తీసుకుంటున్నారు?",
    text_ml: "നിങ്ങൾ ഇതിനകം ഏത് മരുന്നാണ് കഴിക്കുന്നത്?",
    text_bn: "আপনি ইতিমধ্যে কোন ওষুধ খাচ্ছেন?",
    text_or: "ଆପଣ ପୂର୍ବରୁ କେଉଁ ଔଷଧ ନେଉଛନ୍ତି?",
    text_as: "আপুনি ইতিমধ্যে কোন ঔষধ লৈ আছে?",
    text_mr: "तुम्ही आधीच कोणती औषधे घेत आहात?",
    text_ur: "آپ پہلے سے کون سی دوا لے رہے ہیں؟",
    text_bho: "रउआ पहिले से कौन दवा लेत बानी?",
    text_mai: "अहाँ पहिने सँ कोन दवाई लए रहल छी?",
    text_ne: "तपाईं पहिले नै कुन औषधि सेवन गर्दै हुनुहुन्छ?",
    text_mni: "নহাক্না হৌজিক্কী মমাংদগী করি অশিবা চাইরিবগে?",
    text_brx: "नोंथां गेदेबां मा औषध लाना दं?",
  },

  {
    id: "medical_history",
    kind: "fixed",
    type: "multi",
    text: "Medical history (choose all that apply)",
    text_kn: "ವೈದ್ಯಕೀಯ ಇತಿಹಾಸ (ಅನ್ವಯವಾಗುವುದನ್ನೆಲ್ಲಾ ಆಯ್ಕೆ ಮಾಡಿ)",
    text_hi: "चिकित्सा इतिहास (लागू सभी चुनें)",
    text_ta: "மருத்துவ வரலாறு (பொருந்தும் அனைத்தையும் தேர்வு செய்யவும்)",
    text_te: "వైద్య చరిత్ర (వర్తించే వాటన్నింటినీ ఎంచుకోండి)",
    text_ml: "മെഡിക്കൽ ചരിത്രം (ബാധകമായവയെല്ലാം തിരഞ്ഞെടുക്കുക)",
    text_bn: "চিকিৎসা ইতিহাস (প্রযোজ্য সব বেছে নিন)",
    text_or: "ଚିକିତ୍ସା ଇତିହାସ (ପ୍ରଯୁଜ୍ୟ ସବୁ ବାଛନ୍ତୁ)",
    text_as: "চিকিৎসা ইতিহাস (প্রযোজ্য সকলো বাছক)",
    text_mr: "वैद्यकीय इतिहास (लागू असलेले सर्व निवडा)",
    text_ur: "طبی تاریخ (تمام متعلقہ منتخب کریں)",
    text_bho: "मेडिकल इतिहास (लागू सब चुनल जाव)",
    text_mai: "चिकित्सा इतिहास (लागू सब चुनू)",
    text_ne: "चिकित्सा इतिहास (लागू हुने सबै छान्नुहोस्)",
    text_mni: "মেডিকেল হিস্টোরি (মরম চানা পাম্ববা পুম্নমক খনবিয়ু)",
    text_brx: "मेडिकल हिस्ट्री (बाहागो जायसिन सायख'",
    options: [
      { id: "bp", label: "Blood pressure (BP)", label_kn: "ರಕ್ತದೊತ್ತಡ (BP)", label_hi: "ब्लड प्रेशर (BP)", label_ta: "இரத்த அழுத்தம் (BP)", label_te: "బ్లడ్ ప్రెజర్ (BP)", label_ml: "ബ്ലഡ് പ്രഷർ (BP)", label_bn: "ব্লাড প্রেশার (BP)", label_or: "ବ୍ଲଡ ପ୍ରେସର (BP)", label_as: "ব্লাড প্ৰেচাৰ (BP)", label_mr: "ब्लड प्रेशर (BP)", label_ur: "بلڈ پریشر (BP)", label_bho: "ब्लड प्रेशर (BP)", label_mai: "ब्लड प्रेशर (BP)", label_ne: "ब्लड प्रेसर (BP)", label_mni: "ব্লাড পেশার (BP)", label_brx: "ब्लड प्रेसर (BP)" },
      { id: "diabetes", label: "Diabetes", label_kn: "ಮಧುಮೇಹ", label_hi: "मधुमेह", label_ta: "நீரிழிவு", label_te: "మధుమేహం", label_ml: "പ്രമേഹം", label_bn: "ডায়াবেটিস", label_or: "ମଧୁମେହ", label_as: "ডায়েবেটিছ", label_mr: "मधुमेह", label_ur: "ذیابیطس", label_bho: "मधुमेह", label_mai: "मधुमेह", label_ne: "मधुमेह", label_mni: "ডায়াবেটিস", label_brx: "डायबिटीस" },
      { id: "asthma", label: "Asthma / lung disease", label_kn: "ಆಸ್ತಮಾ / ಶ್ವಾಸಕೋಶ ರೋಗ", label_hi: "अस्थमा / फेफड़ों की बीमारी", label_ta: "ஆஸ்துமா / நுரையீரல் நோய்", label_te: "ఆస్తమా / ఊపిరితిత్తుల వ్యాధి", label_ml: "ആസ്ത്മ / ശ്വാസകോശ രോഗം", label_bn: "হাঁপানি / ফুসফুসের রোগ", label_or: "ଆଜ୍ମା / ଫୁସଫୁସ ରୋଗ", label_as: "হাঁপানি / হাওঁফাওঁৰ ৰোগ", label_mr: "दमा / फुफ्फुसाचा आजार", label_ur: "دمہ / پھیپھڑوں کی بیماری", label_bho: "दमा / फेफड़ा के बीमारी", label_mai: "दमा / फोक्सो के रोग", label_ne: "दम / फोक्सोको रोग", label_mni: "অ্যাজমা / লুঙ গী অনাবা", label_brx: "आज्मा / सासनाय रोग" },
      { id: "heart", label: "Heart disease", label_kn: "ಹೃದಯ ರೋಗ", label_hi: "हृदय रोग", label_ta: "இதய நோய்", label_te: "గుండె జబ్బు", label_ml: "ഹൃദ്രോഗം", label_bn: "হৃদরোগ", label_or: "ହୃଦ୍‌ରୋଗ", label_as: "হৃদৰোগ", label_mr: "हृदयरोग", label_ur: "دل کی بیماری", label_bho: "दिल के बीमारी", label_mai: "हृदय रोग", label_ne: "मुटु रोग", label_mni: "হার্ট গী অনাবা", label_brx: "थुनाय रोग" },
      { id: "thyroid", label: "Thyroid disorder", label_kn: "ಥೈರಾಯ್ಡ್ ಸಮಸ್ಯೆ", label_hi: "थायरॉइड विकार", label_ta: "தைராய்டு கோளாறு", label_te: "థైరాయిడ్ సమస్య", label_ml: "തൈറോയ്ഡ് പ്രശ്നം", label_bn: "থাইরয়েড সমস্যা", label_or: "ଥାଇରଏଡ ସମସ୍ୟା", label_as: "থাইৰয়েড সমস্যা", label_mr: "थायरॉइड विकार", label_ur: "تھائیرائیڈ کی خرابی", label_bho: "थायरॉइड समस्या", label_mai: "थायरॉइड समस्या", label_ne: "थाइरोइड समस्या", label_mni: "থাইরয়েড গী অনাবা", label_brx: "थाइरोइड जोंगना" },
      { id: "none", label: "None of these", label_kn: "ಇವುಗಳಲ್ಲಿ ಯಾವುದೂ ಇಲ್ಲ", label_hi: "इनमें से कोई नहीं", label_ta: "இவற்றில் ஏதுமில்லை", label_te: "వీటిలో ఏదీ లేదు", label_ml: "ഇവയിൽ ഒന്നുമില്ല", label_bn: "এগুলোর কোনোটিই নয়", label_or: "ଏଥିରେ କିଛି ନାହିଁ", label_as: "এনেবোৰৰ এটাও নহয়", label_mr: "यापैकी काहीही नाही", label_ur: "ان میں سے کوئی نہیں", label_bho: "इनमें से कवनो नइखे", label_mai: "एहि मे सँ कोनो नहि", label_ne: "यी मध्ये कुनै होइन", label_mni: "মসিগী মরক্তা অমত্তা নত্তে", label_brx: "बेफोरनि खौसेबा गैया", exclusive: true },
    ],
  },

  {
    id: "previous_records",
    kind: "fixed",
    type: "single",
    text: "Do you have previous medical records?",
    text_kn: "ನಿಮ್ಮ ಹಿಂದಿನ ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳು ಇವೆಯೇ?",
    text_hi: "क्या आपके पास पिछले चिकित्सा रिकॉर्ड हैं?",
    text_ta: "உங்களிடம் முந்தைய மருத்துவப் பதிவுகள் உள்ளனவா?",
    text_te: "మీ వద్ద మునుపటి వైద్య రికార్డులు ఉన్నాయా?",
    text_ml: "നിങ്ങളുടെ മുൻ മെഡിക്കൽ റെക്കോർഡുകൾ ഉണ്ടോ?",
    text_bn: "আপনার আগের মেডিকেল রেকর্ড আছে কি?",
    text_or: "ଆପଣଙ୍କ ପାଖରେ ପୂର୍ବ ଚିକିତ୍ସା ରେକର୍ଡ ଅଛି କି?",
    text_as: "আপোনাৰ আগৰ মেডিকেল ৰেকৰ্ড আছে নেকি?",
    text_mr: "तुमच्याकडे मागील वैद्यकीय नोंदी आहेत का?",
    text_ur: "کیا آپ کے پاس پچھلے میڈیکل ریکارڈ ہیں؟",
    text_bho: "रउआ लगे पहिले के मेडिकल रिकॉर्ड बा?",
    text_mai: "अहाँ लग पहिनेक मेडिकल रिकॉर्ड अछि?",
    text_ne: "तपाईंसँग पहिलेका मेडिकल रेकर्ड छन्?",
    text_mni: "নহাক্কী মমাংগী মেডিকেল রেকর্ড লৈব্রা?",
    text_brx: "नोंथांनि गिबां मेडिकल रेकर्ड दं ना?",
    options: [
      { id: "yes", label: "Yes", label_kn: "ಹೌದು", label_hi: "हाँ", label_ta: "ஆம்", label_te: "అవును", label_ml: "അതെ", label_bn: "হ্যাঁ", label_or: "ହଁ", label_as: "হয়", label_mr: "होय", label_ur: "ہاں", label_bho: "हँ", label_mai: "हँ", label_ne: "हो", label_mni: "হোয়", label_brx: "नंगौ" },
      { id: "no", label: "No", label_kn: "ಇಲ್ಲ", label_hi: "नहीं", label_ta: "இல்லை", label_te: "కాదు", label_ml: "ഇല്ല", label_bn: "না", label_or: "ନା", label_as: "নহয়", label_mr: "नाही", label_ur: "نہیں", label_bho: "नइखे", label_mai: "नहि", label_ne: "होइन", label_mni: "নত্তে", label_brx: "नङा" },
    ],
  },

];
